### ISSUE TITLE
error on human3.6m annotation files

### ISSUE THREAD

**Issue by sjtu-cx** [mkocabas/EpipolarPose#10]
Hello, Thanks for your great work.
I am trying to train human3.6m dataset with your code. I have downloaded the human 3.6m dataset from the website and use your provided script to extract images.But when I train the model, I find the image path in the annotation file(both train-fs.pkl and train-ss.pkl) doesn't match my image path.
For example:
the image path in the annotation file is: 'h36m/images/S1/Photo_1.58860488/000781.jpg'
However, I can only find the path 'h36m/images/S1/TakingPhoto_1.58860488/000781.jpg' ,which is the most similar one to the given path.
I wonder whether you make some changes to the image path when generating annotation files, or can you provide the  annotation preparation script?
Thank you very much!

**Comment by mkocabas** [comment]
Hi @sjtu-cx,

Thanks for your interest in our work. I forgot to note it but naming of some S1 video files is different than other subjects. All you need to is renaming them to match the path in annotation files. As far as I remember, `photo` and `walkdog` actions are problematic, others should be fine.

**Comment by sjtu-cx** [comment]
Thanks for your quick reply! I rename the path and now it works!

**Comment by sjtu-cx** [comment]
Hello!
I notice that in dataset.h36m.py, you also implement the code to get data from multi-view cameras.
`        if self.is_train and self.cfg.DATASET.TRI:
            # select a random camera from db
            cam_1 = np.random.randint(self.num_cams)
            # select a neighboring camera
            cam_2 = self.cam_config[cam_1][0] if random.random() <= 0.5 else self.cam_config[cam_1][1]

            # get db records for each view
            db_rec_1 = copy.deepcopy(self.db[cam_1][idx])
            db_rec_2 = copy.deepcopy(self.db[cam_2][idx])

            # there you go
            bundle_1 = self.get_data(db_rec_1)
            bundle_2 = self.get_data(db_rec_2)

            return {'cam_1': bundle_1, 'cam_2': bundle_2}`
So can you provide the annotation files with multi-view camera informations?
Thanks！
