### ISSUE TITLE
Ubuntu 18

### ISSUE THREAD

**Issue by KevinKons** [mkocabas/EpipolarPose#13]
Does it work on ubuntu 18? I have a problem with ubuntu 16 on my laptop.

**Comment by mkocabas** [comment]
Yes, it works! I am using it with Ubuntu 18.04 currently.

**Comment by KevinKons** [comment]
Nice! wich version of cuda are you using?

**Comment by mkocabas** [comment]
I am using 10.1 but it doesn't matter if you are using the correct the pytorch version which is >1.0 in this repo. Besides if you install pytorch using the official installation guide, it will install the compatible cudatoolkit along with pytorch.

**Comment by KevinKons** [comment]
Understood! Thanks for the support!
