### ISSUE TITLE
Which file showing the trangulation from 2D skeletion points?

### ISSUE THREAD

**Issue by huge123** [mkocabas/EpipolarPose#17]
Thanks for opening source codes. However, in the self-supervise setting, I could not find the codes using the model to predict 2D pose and subsequently triangulating 3D joints as the label, so I wonder if you perform the triangulations offline?

And what the parameter cfg.DATASET.TRI means, dose it means using triangulation or not?  if so, why it is set false in 'train-ss.yml'?

Looking forward to your reply, thanks.

**Comment by mkocabas** [comment]
Hi @huge123,

Thanks for your interest! 

We are performing the triangulations offline as we stated in the paper. I couldn't have time to test and upload the triangulation part during the release. I will provide them soon and let you know about it.

> And what the parameter cfg.DATASET.TRI means, dose it means using triangulation or not? if so, why it is set false in 'train-ss.yml'?

Thanks for pointing this out. It's a mistake indeed. I will fix it when I update the repo with triangulation part.

Best,
