### ISSUE TITLE
Can not access to the script for extracting images from h36m videos

### ISSUE THREAD

**Issue by huge123** [mkocabas/EpipolarPose#18]
I have downloaded the Human3.6m videos, and want to extract the images as the instructions, but I could not access to the scripts. Could you share in other ways or just upload to the repository? Thanks

**Comment by mkocabas** [comment]
Hi @huge123,

Thanks for your interest! The link to the script is provided in the [data preparation](https://github.com/mkocabas/EpipolarPose#data-preparation) section under readme.

**Comment by JiatengLiu** [comment]
@huge123   Hello, could you please provide the directory and file name of the video you downloaded? I'm not sure how to place the corresponding file.
