### ISSUE TITLE
About the triangulation algorithm

### ISSUE THREAD

**Issue by StatML** [mkocabas/EpipolarPose#19]
Hi, @mkocabas Thanks for sharing your wonderful project! I have a question about triangulation. To my knowledge, both the camera rotation and translation parameters are needed to use the polynomial triangulation algorithm. But it seems your paper did not tell how to derive the camera translation parameters, and your codes do not show how to call the function `polynomial_triangulation`.  Can you share some experience or supplement some demo of calling `polynomial_triangulation`? Thx a lot!

**Comment by mkocabas** [comment]
Hi @StatML,

Thanks for your interest.

> To my knowledge, both the camera rotation and translation parameters are needed to use the polynomial triangulation algorithm.

Yes, you are right we need camera parameters to perform triangulation. But one can use predicted human pose as the calibration target to obtain rotation and translation of the cameras. Note that translation is up to a scale.  

> But it seems your paper did not tell how to derive the camera translation parameters

Not really, we explain it in detail in section 3.1 4th paragraph in the paper. Please refer to that section.

> your codes do not show how to call the function polynomial_triangulation.

You are right, I will update the repo soon. Please refer to my reply in issue https://github.com/mkocabas/EpipolarPose/issues/18.

Best,

**Comment by ericzw** [comment]
@mkocabas 
Hi, I met the same problem.
I want to know how to use  the function polynomial_triangulation.
Can you give us more details?
