### ISSUE TITLE
joints-alignment between MPII and H36M (thorax)

### ISSUE THREAD

**Issue by wangzheallen** [mkocabas/EpipolarPose#20]
Hi mkocabas,

I found you pre-processing code not aligning the same way as in integral pose https://github.com/mks0601/Integral-Human-Pose-Regression-for-3D-Human-Pose-Estimation/blob/master/data/Human36M/Human36M.py#L54

They are trying to get the thorax from left shoulder and right shoulder.
However, in  your case, https://github.com/mkocabas/EpipolarPose/blob/master/lib/dataset/JointIntegralDataset.py, you directly have thorax in your H36M set. 

May I ask you preprocess in advance or just treat the thorax as Spine1(which is most near thorax) in H36M? Otherwise have you notice any big difference using different thorax handle strategy?

Best,
Zhe

**Comment by mkocabas** [comment]
Hi @wangzheallen,

We are using the annotations provided by [this repo](https://github.com/una-dinosauria/3d-pose-baseline), and thorax is available. However, calculating the thorax from shoulder locations should give fairly similar results.

> I found you pre-processing code not aligning the same way as in integral pose https://github.com/mks0601/Integral-Human-Pose-Regression-for-3D-Human-Pose-Estimation/blob/master/data/Human36M/Human36M.py#L54

Btw, the code you linked isn't the original implementation and I am not sure why they are doing this since thorax should be available in the original annotations.

**Comment by wangzheallen** [comment]
Thanks for the reply @mkocabas 
emmm, seems there are two kinds of processing:
https://github.com/xingyizhou/pytorch-pose-hg-3d/blob/master/src/lib/datasets/h36m.py#L140
also suggests constructing new 'thorax'.

however in the official integral pose regression they did not use any of these transformation:
https://github.com/JimmySuen/integral-human-pose/blob/master/pytorch_projects/integral_human_pose/core/loader.py

which confuses me a lot. anyway, I will look into the original annotation.

**Comment by wangzheallen** [comment]
I visualize the joints from MPII and H36M, and found that there are difference on the joint definition. (Spine in H36M is not defined while for MPII there are upper neck and thorax which corresponds only one neck joint in H36M)
![mpii](https://user-images.githubusercontent.com/5278256/60989230-38cd1980-a2fa-11e9-970d-02f8f28ebbf7.png)
![h36m](https://user-images.githubusercontent.com/5278256/60989231-38cd1980-a2fa-11e9-8de5-d20849f96f5e.png)

**Comment by mkocabas** [comment]
Thanks for the clarification!
