### ISSUE TITLE
About camera parameters

### ISSUE THREAD

**Issue by sta105** [mkocabas/EpipolarPose#21]
Hi mkocabas,

Camera intrinsic and extrinsic are saved in train-xx.pkl files, but could you tell me how do you get those parameters from human3.6m dataset?  Thanks:)

**Comment by mkocabas** [comment]
Hi @sta105,

We are using the camera parameters provided by [this repo](https://github.com/una-dinosauria/3d-pose-baseline). Execute the commands in this part of the [readme](https://github.com/una-dinosauria/3d-pose-baseline#first-of-all) and you will get the camera parameters in a hdf5 file named `cameras.h5`.

Best,
