### ISSUE TITLE
whether to use camera information in fully-supervise training

### ISSUE THREAD

**Issue by yuzhenbo** [mkocabas/EpipolarPose#23]
Can you use camera information like intrinsic parameters in fully supervised training, it seems that you do not use any camera information.

However, you say you use GT intrinsinc camera paremeters in fc-train,  i do not found any camera parameters can be used in either training process or valid process.

Btw,  i found there is no different between integral loss and fc-train  in this paper.  Am i right?

**Comment by mkocabas** [comment]
The training protocol is identical to integral loss, there is no difference. Hence we follow the same exact procedure.
