### ISSUE TITLE
want to change the architecture to actual integral pose repos 

### ISSUE THREAD

**Issue by sezan92** [mkocabas/EpipolarPose#27]
Hello, I want to load the weights trained by integral human pose repository, on the repository you based your work on . but  i will have to change the network configuration to do that. can you guide me how to change your configuration to that of the original repository?

**Comment by mkocabas** [comment]
I didn't inspect the checkpoint file they provided but model definition should be similar to ours. You can check the dimension of the weight tensors and rename the modules accordingly to load the weights.
