### ISSUE TITLE
can you explain the postprocessing functions like show3Dpose and drawskeleton ?

### ISSUE THREAD

**Issue by sezan92** [mkocabas/EpipolarPose#28]
can you explain the postprocessing functions like show3Dpose and drawskeleton ? I need to know them to see if the model is problematic or the visualizaition funcitons?

**Comment by mkocabas** [comment]
These are visualization functions to see the predictions of the model. `show3Dpose` function creates a 3D coordinate systems and draw the predicted skeleton in this space. `drawskeleton` is for visualizing the 2D projection of predicted skeleton in image space.
