### ISSUE TITLE
Training data for 2D pose estimation

### ISSUE THREAD

**Issue by umariqb** [mkocabas/EpipolarPose#29]
Hi Muhammad,

Do you fine-tune your 2D pose estimation model on Human3.6M? Or just use a model pre-trained on MPII and keep it fixed?

Thanks,
Umar

**Comment by mkocabas** [comment]
Hi @iqbalu,

We didn't finetune the 2D pose model on Human3.6M, it is trained only on MPII and kept fixed.

Best,
Muhammed
