### ISSUE TITLE
something wrong in h36m_extract_frames_from_videos.py

### ISSUE THREAD

**Issue by wanghonghui1998** [mkocabas/EpipolarPose#35]
h36m_extract_frames_from_videos.py failed to extract images.
The error is: Could not open file : /data/dataset/h36m_extract/Images/S1/Smoking.55011271/000001.jpg
av_interleaved_write_frame(): Input/output error

**Comment by wanghonghui1998** [comment]
I found I have no root permission to open the file in /data

**Comment by crowdin001** [comment]
> I found I have no root permission to open the file in /data

请问你有数据集吗？我的数据集中的文件似乎不全
