### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by NguyenDangBinh** [mkocabas/EpipolarPose#4]
dear @mkocabas,
can you send me the result of below?
" You would need Human3.6M data to train or test our model. For Human3.6M data, please download from Human 3.6 M dataset. You would need to create an account to get download permission. After downloading video files, you can run our script to extract images. Then run ln -s <path_to_extracted_h36m_images> ${ROOT}/data/h36m/images to create a soft link to images folder. Currently you can use annotation files we provided in step 4, however we will release the annotation preparation script soon after cleaning and proper testing."

**Comment by mkocabas** [comment]
@NguyenDangBinh, you should download the videos of the Human3.6M dataset. To do this, you need to create an account from their websites.

**Comment by NguyenDangBinh** [comment]
dear,
I am waiting but must be patient so long. my god.

**Comment by NguyenDangBinh** [comment]
dear,
www.vision.imar.ro/human3.6m    notices that:
"Your account has been confirmed. Please be patient while we evaluate your application and activate your account."

**Comment by mkocabas** [comment]
Sorry but there is no way around, maybe you can email to dataset owners.

Since this issue is not related to our repo, I am closing it now.
