### ISSUE TITLE
Human3.6M data,

### ISSUE THREAD

**Issue by NguyenDangBinh** [mkocabas/EpipolarPose#5]
dear, 
I can not take that data. Can you send me that data?

**Comment by mkocabas** [comment]
Dear @NguyenDangBinh,

In the [license page of Human3.6M](https://vision.imar.ro/human3.6m/eula.php) it is clearly stated that:

> This product may only be used by you, and you may not rent, lease, lend, sub-license or transfer the dataset or any of your rights under this agreement to anyone else.

Therefore, it is illegal for us to share our copy with you.
