### ISSUE TITLE
test picture after training

### ISSUE THREAD

**Issue by NguyenDangBinh** [mkocabas/EpipolarPose#8]
dear,
I mean that testing my picture after training but demo.ipynb is run before training.
thank you so much.

**Comment by mkocabas** [comment]
Dear @NguyenDangBinh,

In order to run [demo.ipynb](demo.ipynb), you need a pretrained model at hand. The demo notebook is a minimally working example to run a pretrained model on a sample image.

**Comment by NguyenDangBinh** [comment]
dear,
I mean that after training, how are the result too different?

**Comment by NguyenDangBinh** [comment]
dear,
After I had completed training mpii dataset, what should I have done for more understand this repo?
